# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sltwo"
client_id = "9deb0cbb76cd6c9c347e76c265ecf59e"
application_url = "https://sherman-enterprises-colony-loop.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sherman-enterprises-colony-loop.trycloudflare.com/auth/callback",
  "https://sherman-enterprises-colony-loop.trycloudflare.com/auth/shopify/callback",
  "https://sherman-enterprises-colony-loop.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sltwoo.myshopify.com"
